version: '3'

services:
  # Description of Containers:
  #
  #   authproxy   This is the oauth2_proxy container
  #   upstream    This is the upstream app that is protected by the oauth2_proxy
  #

  # Google OAuth Proxy
  authproxy:
    build: ../..
    networks:
      demo-net:
    ports:
      - "4180:4180"
    command: --cookie-secure=false --upstream="http://upstream:80" --http-address="0.0.0.0:4180" --redirect-url="http://docker.example.com/oauth2/callback" --email-domain="example.com"
    environment:
      OAUTH2_PROXY_COOKIE_SECRET: totally-secret-key
      OAUTH2_PROXY_COOKIE_DOMAIN: docker.example.com
      OAUTH2_PROXY_CLIENT_ID: client_id
      OAUTH2_PROXY_CLIENT_SECRET: client_secret

  # NGINX example app
  upstream:
    build: ../nginx
    networks:
      demo-net:
    ports:
      - "8888:80"
    depends_on:
      - authproxy

networks:
  demo-net:

# vim: sw=2 sts=2 et
